"""baseline schema

Revision ID: e671bf5ba339
Revises: 
Create Date: 2026-08-10 13:36:52.152409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e671bf5ba339'
down_revision: Union[str, Sequence[str], None] = 'ab5ddd3d013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.

    NOTE: the ix_documents_session_id index and the documents.session_id ->
    chat_sessions FK (ondelete=CASCADE) that this migration originally also
    created here have been removed — ab5ddd3d013b now creates both of those
    directly as part of the initial table creation, so recreating them here
    would fail with "already exists" for any database going through the full
    chain from empty. The ALTER COLUMN statements below are left as-is: they
    are idempotent (safe to re-apply even when the target state already
    matches) and this keeps the historical shape of this migration for any
    database that was already stamped at this revision before ab5ddd3d013b
    existed.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=False)
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('documents', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'processing'::character varying"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.

    NOTE: mirrors upgrade() above — the FK/index drop+recreate pair that
    used to run here has been removed since ab5ddd3d013b now owns creating
    ix_documents_session_id and the CASCADE FK; downgrading past this
    revision no longer needs to touch either (ab5ddd3d013b's own downgrade()
    drops them when the chain is unwound that far).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'processing'::character varying"))
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_chunks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
